apueerr.o: apueerr.c apue.h
	gcc -c apueerr.c -o apueerr.o
apuelog.o: apuelog.c apue.h
	gcc -c apuelog.c -o apuelog.o
pathalloc.o: pathalloc.c apue.h
	gcc -c pathalloc.c -o pathalloc.o
openmax.o: openmax.c apue.h
	gcc -c openmax.c -o openmax.o

clean:
	rm *.o